[package]
name = "advent-2018"
version = "0.1.0"
authors = ["Brandon Edens <brandonedens@gmail.com>"]
edition = "2018"

[dependencies]
levenshtein = "1.0.3"
regex = "1.1.0"
lazy_static = "1.2.0"
chrono = "0.4.6"
ansi_term = "0.11.0"
